# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Asignaturas\Compilacion\Proyectos\Cool Type Inferer\uis\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(843, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Qt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupCode = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.groupCode.setFont(font)
        self.groupCode.setObjectName("groupCode")
        self.gridLayout = QtWidgets.QGridLayout(self.groupCode)
        self.gridLayout.setObjectName("gridLayout")
        self.textCode = CodeEditor(self.groupCode)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.textCode.setFont(font)
        self.textCode.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textCode.setObjectName("textCode")
        self.gridLayout.addWidget(self.textCode, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupCode)
        self.groupResults = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.groupResults.setFont(font)
        self.groupResults.setObjectName("groupResults")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupResults)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textResults = QtWidgets.QTextBrowser(self.groupResults)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textResults.setFont(font)
        self.textResults.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textResults.setObjectName("textResults")
        self.gridLayout_2.addWidget(self.textResults, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupResults)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(795, 40))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ui-tab--plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon1)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionSaveFile = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFile.setIcon(icon2)
        self.actionSaveFile.setObjectName("actionSaveFile")
        self.actionLoadFile = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/blue-folder-open-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadFile.setIcon(icon3)
        self.actionLoadFile.setObjectName("actionLoadFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/arrow-000.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionHowToUse = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/lifebuoy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHowToUse.setIcon(icon5)
        self.actionHowToUse.setObjectName("actionHowToUse")
        self.actionAboutAuthors = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAboutAuthors.setIcon(icon6)
        self.actionAboutAuthors.setObjectName("actionAboutAuthors")
        self.actionAboutCoolTypeInferer = QtWidgets.QAction(MainWindow)
        self.actionAboutCoolTypeInferer.setIcon(icon6)
        self.actionAboutCoolTypeInferer.setObjectName("actionAboutCoolTypeInferer")
        self.actionSaveFileAs = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/disk--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFileAs.setIcon(icon7)
        self.actionSaveFileAs.setObjectName("actionSaveFileAs")
        self.actionAnalyse = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyse.setIcon(icon8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionAnalyse.setFont(font)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionLoadFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveFile)
        self.menuFile.addAction(self.actionSaveFileAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHowToUse)
        self.menuHelp.addAction(self.actionAboutAuthors)
        self.menuHelp.addAction(self.actionAboutCoolTypeInferer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAnalyse)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionLoadFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSaveFile)
        self.toolBar.addAction(self.actionSaveFileAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHowToUse)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cool Type Inferer"))
        self.groupCode.setTitle(_translate("MainWindow", "Code"))
        self.groupResults.setTitle(_translate("MainWindow", "Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Herramientas"))
        self.actionNewFile.setText(_translate("MainWindow", "New File"))
        self.actionNewFile.setStatusTip(_translate("MainWindow", "New File"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSaveFile.setText(_translate("MainWindow", "Save File"))
        self.actionSaveFile.setStatusTip(_translate("MainWindow", "Save File"))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionLoadFile.setText(_translate("MainWindow", "Load File"))
        self.actionLoadFile.setStatusTip(_translate("MainWindow", "Load File"))
        self.actionLoadFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionHowToUse.setText(_translate("MainWindow", "How To Use"))
        self.actionHowToUse.setStatusTip(_translate("MainWindow", "How to Use"))
        self.actionAboutAuthors.setText(_translate("MainWindow", "About Authors"))
        self.actionAboutAuthors.setStatusTip(_translate("MainWindow", "About Authors"))
        self.actionAboutCoolTypeInferer.setText(_translate("MainWindow", "About Cool Type Inferer"))
        self.actionAboutCoolTypeInferer.setStatusTip(_translate("MainWindow", "About Cool Type Inferer"))
        self.actionSaveFileAs.setText(_translate("MainWindow", "Save File As"))
        self.actionSaveFileAs.setStatusTip(_translate("MainWindow", "Save File As"))
        self.actionAnalyse.setText(_translate("MainWindow", "Analyse"))
        self.actionAnalyse.setToolTip(_translate("MainWindow", "Analyse"))
        self.actionAnalyse.setStatusTip(_translate("MainWindow", "Analyse"))
        self.actionAnalyse.setShortcut(_translate("MainWindow", "F5"))

from .codeeditor import CodeEditor
